### ISSUE TITLE
Move uvicorn/FASTAPI app to main

### ISSUE THREAD

**Issue by RobertLD** [GetLouied/OTCINFO#2]
Running your ASGI webservice is something that should happen in your main.py file. Having it here is a little confusing. 

https://github.com/GetLouied/OTCINFO/blob/c3d5e96c0f999a2afafa23e38ec56ed5b7f2f84c/alerts.py#L26-L28

You can replace this line with a router and then import that router into your main function
`app = FastAPI()`

**Comment by GetLouied** [comment]
Completed.
